<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /*private pastEventfunction(){
        $query = $em->createQuery('SELECT u FROM MyProject\Model\User u WHERE u.age > 20');
        $pastEvent = $query->getResult();
       
    }*/
}
